### ISSUE TITLE
Problem with graphics

### ISSUE THREAD

**Issue by jeffersonpimenta** [SCADA-LTS/Scada-LTS#1005]
I have one issue with graphics inside point details:

When i use the "Latest" or "Inception" function, it works just fine.
![image](https://user-images.githubusercontent.com/11169349/66001024-081efb00-e477-11e9-884c-611ab1335630.png)

But when i try to put custom intervals it didn't works.

My last log was

Exception in thread "http-bio-8080-exec-4" java.lang.OutOfMemoryError: Java heap space
WARN  2019-10-01 18:14:28,055 (net.bull.javamelody.Log4JLogger.warn:45) - exception while collecting data: java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner; 
java.lang.NoSuchMethodError: sun.nio.ch.DirectBuffer.cleaner()Lsun/misc/Cleaner;
	at net.bull.javamelody.RrdNioBackend.unmapFile(RrdNioBackend.java:102)
	at net.bull.javamelody.RrdNioBackend.close(RrdNioBackend.java:167)
	at org.jrobin.core.RrdDb.close(RrdDb.java:443)
	at org.jrobin.core.RrdDbPool.release(RrdDbPool.java:196)
	at net.bull.javamelody.JRobin.addValue(JRobin.java:354)
	at net.bull.javamelody.Collector.collectJRobinValues(Collector.java:511)
	at net.bull.javamelody.Collector.collectJavaInformations(Collector.java:381)
	at net.bull.javamelody.Collector.collect(Collector.java:319)
	at net.bull.javamelody.Collector.collectWithoutErrors(Collector.java:305)
	at net.bull.javamelody.Collector.collectLocalContextWithoutErrors(Collector.java:294)
	at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:56)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Exception in thread "http-bio-8080-exec-5" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-bio-8080-exec-10" java.lang.OutOfMemoryError: Java heap space
WARN  2019-10-01 18:16:38,998 (net.bull.javamelody.Log4JLogger.warn:45) - exception while collecting data: java.lang.OutOfMemoryError: Java heap space 
java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-bio-8080-AsyncTimeout" Exception in thread "http-bio-8080-exec-11" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space

**Comment by Limraj** [comment]
Hi @jeffersonpimenta,
The probable cause of this problem was either the lack of RAM for the virtual machine, or too little memory allocated with the -Xmx parameter in Java/Tomcat options, e.g.:
-Xmx512M

If you have questions about this topic, you can open an issue, you can ask here.

Regards,
Kamil Jarmusik
