### ISSUE TITLE
ConcurrentModificationException in ContentGenerator.generateContent

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#1088]
## Actual Behavior
When the event buffer is enabled, an exception occurs ConcurrentModificationException when loading the event list into view.

## Expected Behavior
Secure against the exception ConcurrentModificationException.

## Specifications
  - Version: v2.0.0
  - Platform: linux
  - Subsystem: open jdk 1.8, mysql 5.7

**Comment by Limraj** [comment]
> java.util.ConcurrentModificationException
> 	at java.util.concurrent.CopyOnWriteArrayList$COWSubList.checkForComodification(CopyOnWriteArrayList.java:1277)
> 	at java.util.concurrent.CopyOnWriteArrayList$COWSubList.size(CopyOnWriteArrayList.java:1317)
> 	at java.util.AbstractCollection.isEmpty(AbstractCollection.java:86)
> 	at org.apache.el.parser.AstEmpty.getValue(AstEmpty.java:54)
> 	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
> 	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:950)
> 	at org.apache.jsp.WEB_002dINF.snippet.alarmList_jsp._jspx_meth_c_005fif_005f5(alarmList_jsp.java:511)
> 	at org.apache.jsp.WEB_002dINF.snippet.alarmList_jsp._jspService(alarmList_jsp.java:157)
> 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
> 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
> 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
> 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:743)
> 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
> 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
> 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
> 	at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.bull.javamelody.JspWrapper.invoke(JspWrapper.java:150)
> 	at net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:286)
> 	at com.sun.proxy.$Proxy48.forward(Unknown Source)
> 	at com.serotonin.web.content.ContentGenerator.generateContent(ContentGenerator.java:48)
> 	at com.serotonin.mango.web.dwr.BaseDwr.generateContent(BaseDwr.java:314)
> 	at br.org.scadabr.view.component.AlarmListComponent.generateContent(AlarmListComponent.java:65)
> 	at com.serotonin.mango.web.dwr.ViewDwr.addCustomComponentState(ViewDwr.java:294)
