### ISSUE TITLE
Fixed permission for import/export project

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2005]
**Description**
The project import function is partially secured, but clicking by the user leads to the first stage of importing the project. Full security for the import function should be added.

**To Reproduce**

1. **Import/Export -> Export Project (Download)**
1.1 Login as usr_1;
1.2 Go to '/ScadaBR/emport.shtm';
1.3 Click on 'Export Project' in section 'Export Project (Download)';
1.4 If it generates a configuration file, it means an error;

2. **Import/Export -> Import Project (Upload)**
2.1 Create user as usr_1;
2.2 Login on usr_1;
2.3. Go to '/ScadaBR/emport.shtm'
2.4. In section 'Import Project (Upload)' click on 'Choose file' select file and click 'Send'
2.5. Click 'Import' -> unknown error;

3.  **Import/Export -> Import Project (Upload)** first login as admin, next login usr_1;
3.1 Login as admin;
3.2 Go to '/ScadaBR/emport.shtm';
3.3 Click 'Choose file' and select file *.zip, and click 'Send' as tab_1;
3.4 Open other tab_2, logout admin, and login usr_1;
3.5 Go back to tab_1;
3.6 Click 'Import';
3.7 Go to 'login.shtm', and try login as usr_1 -> "Cannot find user Id" -> error;

4. **Import/Export -> Export**
4.1 Login on usr_1;
4.2. Go to '/ScadaBR/emport.shtm';
4.3 Click checkbox in section 'Export' and click 'Generate JSON';
4.4 If json with data is generated, it means an error;

5. **Import/Export -> Import**
5.1 Login on usr_1;
5.2. Go to '/ScadaBR/emport.shtm';
5.3 Past json in 'data' and click 'Import' in section 'Import' (no 'Import Project (Upload)');
5.4 If the import process starts, it means an error;

6. **API export config**
6.1 Go to '/ScadaBR/api/export/config/';
6.2 If it generates a configuration file, it means an error, the response should be http 401;

**Specification:**
 - Version 2.6.10

**Comment by grzesiekb** [comment]
After switching to the branch with this task, I get an error:
Exception in thread "pool-3-thread-16" java.lang.NullPointerException
	at com.serotonin.mango.rt.maint.WorkItemMonitor.run(WorkItemMonitor.java:45)
	at com.serotonin.timer.TimerTask.run(TimerTask.java:143)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by grzesiekb** [comment]
Next error:
Exception in thread "pool-3-thread-16" java.lang.NullPointerException
	at com.serotonin.mango.rt.maint.WorkItemMonitor.run(WorkItemMonitor.java:45)
	at com.serotonin.timer.TimerTask.run(TimerTask.java:143)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
