### ISSUE TITLE
DB connection problem

### ISSUE THREAD

**Issue by jeffersonpimenta** [SCADA-LTS/Scada-LTS#936]
Hi, i have this issue with new version of ScadaLTS:

Unexpected exception resolving reference
java.sql.SQLException
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:710)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:644)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:466)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:143)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
	at org.apache.tomcat.jdbc.pool.DataSourceFactory.createDataSource(DataSourceFactory.java:554)
	at org.apache.tomcat.jdbc.pool.DataSourceFactory.getObjectInstance(DataSourceFactory.java:242)
	at org.apache.naming.factory.ResourceFactory.getObjectInstance(ResourceFactory.java:142)
	at javax.naming.spi.NamingManager.getObjectInstance(NamingManager.java:321)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:843)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.catalina.core.NamingContextListener.addResource(NamingContextListener.java:1110)
	at org.apache.catalina.core.NamingContextListener.createNamingContext(NamingContextListener.java:689)
	at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:273)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5472)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1091)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1980)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:246)
	... 36 more

I'm using v0.0.9.8_1, Ubuntu server 16.04, tomcat7 and my env.properties is like:

db.type=mysql
db.datasource=true
db.datasourceName=java:comp/env/jdbc/scadalts
db.url=jdbc:mysql://localhost:3306/scadalts
db.username=root
db.password=scada
db.pool.maxActive=10
db.pool.maxIdle=10

When i try to use derby as a database i can't connect too.

Thanks in advance!

**Comment by jeffersonpimenta** [comment]
Solution:
env.properties like this

db.type=mysql
#db.datasource=true
#db.datasourceName=java:comp/env/jdbc/scadalts
db.url=jdbc:mysql://localhost:3306/scadalts
db.username=root
db.password=scada
db.pool.maxActive=10
db.pool.maxIdle=10
#db.update.log.dir=logs
#db.upgrade.check=false
